"""Post-change validation: does 95d2111 (the credible-rival-path gate on block_opportunity /
DENIAL) actually change anything besides the DENIAL label itself? Compares the pre-change
baseline (data/draft_simulation_trials/baseline_pre_95d2111/*.json, preserved before
regenerating) against a freshly re-simulated post-95d2111 baseline
(data/draft_simulation_trials/*.json, regenerated by run_draft_validation.py against current
code), across every layer the leave-one-force-out ablation experiment already proved denial
has NO causal reach into (TAV, candidate ordering, draft trajectory, roster/build outcomes),
plus the one layer it's supposed to affect (the DENIAL flag itself).

This is confirmation, not discovery -- the causal separation was already proven structurally
(team_acquisition_value's own formula has no denial term) and empirically (a small monkeypatch
simulation, the real-board CandidateSnapshot-level regression test in
test_cdme_certification.py, and verify_denial_boundary_change.py's block_opportunity count
match). This script closes the loop at the scale the methodology calls for: a full 12-chair
re-simulation and the same counterfactual/roster diagnostics used to certify baseline-12chair-
v1 in the first place, not just unit-level proof.

Not part of the automated test suite (needs the gitignored trial JSON on both sides -- the
preserved pre-change baseline and a fresh post-change run). Run by hand.

CORRECTION, discovered while actually running this: the FIRST run of this script (against
data/draft_simulation_trials/baseline_pre_95d2111/ as originally backed up -- i.e. baseline-
12chair-v1 itself, generated early in this session) reported real trajectory/roster/
counterfactual divergences. Both turned out to be contamination in the comparison ANCHOR, not
effects of 95d2111:
  1. baseline-12chair-v1 predates 180d699 (the tie-order-determinism fix, a separate, already-
     landed and already-authorized commit) -- so it carried arbitrary player_id tie-breaking
     that the current code no longer has, unrelated to denial entirely.
  2. A second, independent bug: run_draft_validation.py's own DataMerger construction never
     called set_league_format() (unlike app.py, which does on every rerun -- see app.py's own
     comment: "confirmed: one real player's trade_value swung ~2.7x purely on that accident").
     Without a format hint, a player appearing in more than one format-specific Dynasty
     Rankings export (PPR vs TE-premium vs superflex) gets resolved by "whichever file sorts
     last by (mtime, name)" -- deterministic for fixed file mtimes, but not pinned to league
     format, so two separate regenerations of the SAME trial config can silently draft
     different players if those mtimes shift between runs (confirmed: they did). Fixed
     directly in run_draft_validation.py (each config now builds its own DataMerger with an
     explicit league_format matching that trial's own real league).

With BOTH contaminations controlled for (a same-tie-order-fix-generation ANCHOR, both sides
using the format-corrected DataMerger), the comparison this script exists to run confirmed
exactly what the module docstring above claims: trajectory, roster diagnostics, and
counterfactual nodes byte-identical; only block_opportunity flag density differs. OLD_DIR
below MUST point at a baseline generated with the SAME tie-order/format-hint code as whatever
HEAD you're comparing against minus only the change under test -- never assume an old,
previously-backed-up data/draft_simulation_trials/ snapshot still qualifies without checking
its generation commit first.
"""

from __future__ import annotations

import json
from pathlib import Path

import data_merger as dm
import draft_room as dr
import roster_diagnostics as rd
from draft_counterfactual import compare_trajectory
from draft_simulation import DraftTrajectory, PickRecord

TRIALS_DIR = Path("data/draft_simulation_trials")
OLD_DIR = TRIALS_DIR / "baseline_pre_95d2111"
POSITIONS = ("QB", "RB", "WR", "TE")

TRIAL_LEAGUE_CONFIG = {
    "standard_1qb": dict(teams=12, superflex=False, scoring="ppr", te_premium=False, dynasty=True),
    "superflex": dict(teams=12, superflex=True, scoring="ppr", te_premium=False, dynasty=True),
    "standard_1qb_reversed_slots": dict(teams=12, superflex=False, scoring="ppr", te_premium=False, dynasty=True),
}


def _build_pool_players_db() -> tuple[dm.DataMerger, dict[str, dict]]:
    merger = dm.DataMerger()
    proj = merger.projections
    players_db: dict[str, dict] = {}
    pid = 0
    for pos in POSITIONS:
        sub = proj[proj["position"] == pos].sort_values("trade_value", ascending=False)
        for _, row in sub.iterrows():
            pid += 1
            parts = row["norm_name"].split()
            players_db[str(pid)] = {
                "first_name": parts[0].upper(), "last_name": " ".join(parts[1:]).title(),
                "position": pos, "fantasy_positions": [pos], "team": row.get("team"),
            }
    return merger, players_db


def _load(path: Path) -> DraftTrajectory:
    data = json.loads(path.read_text())
    picks = tuple(PickRecord(**p) for p in data["picks"])
    return DraftTrajectory(config=data["config"], picks=picks)


def _block_count(trajectory: DraftTrajectory) -> tuple[int, int]:
    """(candidates flagged block_opportunity, total candidates seen) across every saved
    snapshot in the trajectory -- direct tally of whatever forces build_snapshot actually
    produced when this trajectory was simulated, no recomputation."""
    flagged, total = 0, 0
    for rec in trajectory.picks:
        for c in rec.snapshot["candidates"]:
            total += 1
            if "block" in (c.get("forces") or []):
                flagged += 1
    return flagged, total


def main() -> None:
    merger, players_db = _build_pool_players_db()
    overall_ok = True

    for label, league_cfg in TRIAL_LEAGUE_CONFIG.items():
        print(f"\n=== {label} ===")
        league = dr.build_mock_league(**league_cfg)
        old_traj = _load(OLD_DIR / f"{label}.json")
        new_traj = _load(TRIALS_DIR / f"{label}.json")

        # 1) Draft trajectory itself: same players, same order, same rosters.
        old_seq = [(r.pick_no, r.roster_id, r.chosen_player_id) for r in old_traj.picks]
        new_seq = [(r.pick_no, r.roster_id, r.chosen_player_id) for r in new_traj.picks]
        trajectory_identical = old_seq == new_seq
        print(f"trajectory identical: {trajectory_identical} ({len(old_seq)} picks each)")
        overall_ok = overall_ok and trajectory_identical
        if not trajectory_identical:
            first_diff = next(i for i, (o, n) in enumerate(zip(old_seq, new_seq)) if o != n)
            print(f"  FIRST DIVERGENCE at index {first_diff}: old={old_seq[first_diff]} new={new_seq[first_diff]}")

        # 2) necessity_label / decision_regime for the chosen candidate at every pick: neither
        #    reads block_opportunity, so must also be identical. serialize_candidate's
        #    "necessity" key holds necessity_label (the string), not the numeric score --
        #    there is no separate numeric field in the serialized snapshot shape.
        def _chosen_necessity(traj):
            out = []
            for r in traj.picks:
                cand = next(c for c in r.snapshot["candidates"] if c["id"] == r.chosen_player_id)
                out.append((cand.get("necessity"), r.decision_regime))
            return out
        necessity_identical = _chosen_necessity(old_traj) == _chosen_necessity(new_traj)
        print(f"necessity/decision_regime identical: {necessity_identical}")
        overall_ok = overall_ok and necessity_identical

        # 3) Roster/build diagnostics: pure function of the trajectory's own picks + a fresh
        #    board recompute -- must match if (1) held.
        old_diag = rd.compute_team_diagnostics(merger, players_db, league, old_traj)
        new_diag = rd.compute_team_diagnostics(merger, players_db, league, new_traj)
        diag_identical = old_diag == new_diag
        print(f"roster diagnostics identical (accumulated/lineup/replacement/holes, all {len(old_diag)} teams): {diag_identical}")
        overall_ok = overall_ok and diag_identical
        if not diag_identical:
            for rid in old_diag:
                if old_diag[rid] != new_diag[rid]:
                    print(f"  DIVERGED roster {rid}: old={old_diag[rid]} new={new_diag[rid]}")

        # 4) Counterfactual/BPA-regret diagnostics: engine choice is read off the trajectory
        #    (identical per (1)), classification reuses necessity_label/near_tie (identical
        #    per (2)) -- must match.
        old_cf = compare_trajectory(merger, players_db, league, old_traj)
        new_cf = compare_trajectory(merger, players_db, league, new_traj)
        old_supported = sum(1 for c in old_cf if c.deviation_supported is True)
        new_supported = sum(1 for c in new_cf if c.deviation_supported is True)
        old_regret = round(sum(c.regret_vs_bpa for c in old_cf), 3)
        new_regret = round(sum(c.regret_vs_bpa for c in new_cf), 3)
        cf_identical = (old_cf == new_cf)
        print(f"counterfactual nodes identical: {cf_identical} (deviation_supported old={old_supported} new={new_supported}, total regret_vs_bpa old={old_regret} new={new_regret})")
        overall_ok = overall_ok and cf_identical

        # 5) The one thing that's SUPPOSED to change: DENIAL/block_opportunity flag density.
        old_flagged, old_total = _block_count(old_traj)
        new_flagged, new_total = _block_count(new_traj)
        print(f"block_opportunity flags: old={old_flagged}/{old_total} ({old_flagged/old_total:.1%})  "
              f"new={new_flagged}/{new_total} ({new_flagged/new_total:.1%})  "
              f"reduction={old_flagged - new_flagged} ({(old_flagged - new_flagged)/old_flagged:.1%} of old flags removed)" if old_flagged else "")

    print("\n=== VERDICT ===")
    if overall_ok:
        print("CONFIRMED: draft trajectories, necessity/decision_regime, roster/build diagnostics, and "
              "counterfactual BPA-regret/deviation-supported classification are all byte-identical between "
              "the pre- and post-95d2111 baselines. The ONLY observed change is DENIAL flag density -- "
              "exactly the intended, scoped effect. KEEP as the current calibration baseline.")
    else:
        print("MISMATCH found outside the DENIAL flag layer -- see above. This means the change had a wider "
              "blast radius than authorized and needs investigation before treating 95d2111 as settled.")


if __name__ == "__main__":
    main()
